version: "3.8"

services:
  api:
    image: 058264543480.dkr.ecr.us-east-1.amazonaws.com/blacklist-api:1.0.0
    restart: always
    ports:
      - 80:5000
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     # Sync shared public files
    #     rm -rf /app/shared/public/*
    #     cp -r /app/public/* /app/shared/public
    #     #
    #     # You can add more commands before startup: compile assets, run migrations, ... if you have
    #     # ...
    #     #
    #     # Start node app
    #     node dist/main.js
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=blacklist-db.cxw6wye0iiw7.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=blacklist_db
    # volumes:
    #   - public_assets:/app/shared/public

# volumes:
#   public_assets: